name: Do Something That Needs Scheduled

on:
  repository_dispatch:
    types: [ do-something ]
  workflow_dispatch:
    inputs:
      text:
        description: 'Text to echo'
        required: false
        default: 'Hello, world!'

jobs:
  build:
    name: Run Some Scheduled Thing
    runs-on: ubuntu-latest
    steps:

      - name: Do Something
        run: echo Doing Something...

      - name: Do Something Based On Triggered Event Data
        run: 'echo "Triggered event text: ${{ github.event.client_payload.text }}"'

      - name: Do Something Based On Manual Input
        run: 'echo "Manual input text: ${{ github.event.inputs.text }}"'